#!/bin/sh

set -e

flatpak remote-add --if-not-exists --system appcenter https://flatpak.elementary.io/repo.flatpakrepo
flatpak install --system --noninteractive appcenter org.gnome.Epiphany//stable || true

flatpak remote-add --if-not-exists --system --filter=/etc/flatpak/freedesktop.filter freedesktop https://flathub.org/repo/flathub.flatpakrepo
flatpak install --system --noninteractive freedesktop org.freedesktop.Platform.GL.default//21.08 || true

#DEBHELPER#

exit 0
