
name: CI

on: [push, pull_request]

jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: docker.io/bilelmoussaoui/flatpak-github-actions
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions@master
      with:
        bundle: "org.gnome.epiphany.flatpak"
        runtime-repo: "https://flatpak.elementary.io/elementary.flatpakrepo"
        manifest-path: "org.gnome.epiphany.yml"
