
name: Merge

on:
  push:
    branches:
      - main

jobs:
  deploy_flatpak:
    name: Deploy Flatpak
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:daily
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
        with:
          bundle: org.gnome.epiphany.flatpak
          manifest-path: org.gnome.epiphany.yml
          repository-name: elementary
          repository-url: https://flatpak.elementary.io/repo.flatpakrepo
          cache-key: "flatpak-builder-${{ github.sha }}"
          branch: daily

      - name: Deploy
        uses: bilelmoussaoui/flatpak-github-actions/flat-manager@v3
        with:
          repository: appcenter
          flat-manager-url: https://flatpak-api.elementary.io
          token: ${{ secrets.FLAT_MANAGER_TOKEN }}
